sudo: false

cache:
  directories:
  - $HOME/.m2

addons:
  apt:
    packages:
    - metacity
    - oracle-java8-installer

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      env: 
        - TARGET=mars
        - DISPLAY=:99.0
        - USER1_GDRIVE_USERNAME=$USER1_GDRIVE_USERNAME
        - USER1_GDRIVE_PASSWORD=$USER1_GDRIVE_PASSWORD
        - USER1_RECOVERY_EMAIL=$USER1_RECOVERY_EMAIL
        - USER2_GDRIVE_USERNAME=$USER2_GDRIVE_USERNAME
        - USER2_GDRIVE_PASSWORD=$USER2_GDRIVE_PASSWORD
        - USER2_RECOVERY_EMAIL=$USER2_RECOVERY_EMAIL        
      before_install:
        - source ./travis/install-maven.sh
        - source ./travis/start-ngrok.sh
      install: true
      before_script:
        - source ./travis/start-metacity.sh
      script:
        - source ./travis/build-mars.sh
      after_script:
        - source ./travis/stop-ngrok.sh
    - language: java
      jdk: oraclejdk8
      env: 
        - TARGET=neon
        - DISPLAY=:99.0
        - USER1_GDRIVE_USERNAME=$USER3_GDRIVE_USERNAME
        - USER1_GDRIVE_PASSWORD=$USER3_GDRIVE_PASSWORD
        - USER1_RECOVERY_EMAIL=$USER3_RECOVERY_EMAIL
        - USER2_GDRIVE_USERNAME=$USER4_GDRIVE_USERNAME
        - USER2_GDRIVE_PASSWORD=$USER4_GDRIVE_PASSWORD
        - USER2_RECOVERY_EMAIL=$USER4_RECOVERY_EMAIL         
      before_install:
        - source ./travis/install-maven.sh
      install: true
      before_script:
        - source ./travis/start-metacity.sh
      script:
        - source ./travis/build-neon.sh
    
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ef692f2d5da17132be34
    on_success: change
    on_failure: always
    on_start: never
