# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tycho build for Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        USER1_GDRIVE_USERNAME: ${{ secrets.USER1_GDRIVE_USERNAME }}
        USER1_GDRIVE_REFRESH_TOKEN: ${{ secrets.USER1_GDRIVE_REFRESH_TOKEN }}
        USER2_GDRIVE_USERNAME: ${{ secrets.USER2_GDRIVE_USERNAME }}
        USER2_GDRIVE_REFRESH_TOKEN: ${{ secrets.USER2_GDRIVE_REFRESH_TOKEN }}            
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      run: xvfb-run -a ./mvnw clean verify -P target-2021-12 --fail-at-end
